<a href="https://colab.research.google.com/github/LuisANDRESdd/Para-ti-mi-ni-a/blob/main/Copia_de_MetodosGroupBy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Inicialización de librerías y DataFrames**

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

# DataFrame de Facturas (Usado para GroupBy)
facturas = pd.DataFrame({
    'folio': (15234, 15235, 15236, 15237, 15238, 15239, 15240, 15241, 15242),
    'sucursal': ('CDMX01', 'MTY01', 'CDMX02', 'CDMX02', 'MTY01', 'GDL01', 'CDMX02', 'MTY01', 'GDL01'),
    'monto': (1420.00, 1532.00, 890.00, 1300.00, 3121.47, 1100.5, 12230.00, 230.85, 1569.00),
    'fecha': (datetime(2019,3,11,17,24), datetime(2019,3,24,14,46), datetime(2019,3,25,17,58),
              datetime(2019,3,27,13,11), datetime(2019,3,31,10,25), datetime(2019,4,1,18,32),
              datetime(2019,4,3,11,43), datetime(2019,4,4,16,55), datetime(2019,4,5,12,59)),
    'cliente': (19234, 19232, 19235, 19233, 19236, 19237, 19232, 19233, 19232)
})

# DataFrame de Población (Usado para Limpieza de NaN)
poblacion = pd.DataFrame({
    'Animal': ('lobo', 'coyote', 'jaguar', 'cerdo salvaje', 'tapir', 'venado', 'ocelote', 'puma'),
    'Norte_I': (12, np.nan, None, 2, 4, 2, 14, 5),
    'Norte_II': (23, 4, 25, 21, 9, 121, 1, 2),
    'Centro_I': (15, 23, 2, 120, 40, 121, 0, 5),
    'Sur_I': (28, 46, 14, 156, 79, 12, 2, np.nan)
}).set_index('Animal')

# DataFrame secundario de otra_poblacion
otra_poblacion = pd.DataFrame({
    'Animal': ('lobo', 'coyote', 'jaguar', 'cerdo salvaje', 'tapir', 'venado', 'ocelote', 'puma'),
    'Norte_I': (12, 4, None, 2, 4, 2, 14, 4),
    'Norte_II': (23, 4, 25, 21, 9, 121, 1, 4),
    'Centro_I': (15, 4, 2, 120, 40, 121, 0, 4),
    'Sur_I': (28, 4, 14, 156, 79, 12, 2, 4)
}).set_index('Animal')

**PARTE 1: Métodos de Agrupamiento (groupby)**

Filtrado de columnas seleccionadas

In [ ]:
gastos_por_cliente = facturas.filter(items=["monto", "cliente"])
gastos_por_cliente

      monto  cliente
0   1420.00    19234
1   1532.00    19232
2    890.00    19235
3   1300.00    19233
4   3121.47    19236
5   1100.50    19237
6  12230.00    19232
7    230.85    19233
8   1569.00    19232

Creación del objeto groupby y visualización de grupos

In [ ]:
clientes = gastos_por_cliente.groupby("cliente")
clientes

Inspección de los índices de los grupos

In [ ]:
print(clientes.groups)

{19232: [1, 6, 8], 19233: [3, 7], 19234: [0], 19235: [2], 19236: [4], 19237: [5]}

Iteración e impresión de grupos individuales

In [ ]:
for nombre_cliente, grupo in clientes:
    print(f"Grupo para cliente: {nombre_cliente}")
    print(grupo)
    print("-" * 50)

Grupo para cliente: 19232
     monto  cliente
1   1532.0    19232
6  12230.0    19232
8   1569.0    19232
--------------------------------------------------
Grupo para cliente: 19233
     monto  cliente
3  1300.00    19233
7   230.85    19233
--------------------------------------------------
Grupo para cliente: 19234
    monto  cliente
0  1420.0    19234
--------------------------------------------------
Grupo para cliente: 19235
   monto  cliente
2  890.0    19235
--------------------------------------------------
Grupo para cliente: 19236
     monto  cliente
4  3121.47    19236
--------------------------------------------------
Grupo para cliente: 19237
    monto  cliente
5  1100.5    19237
--------------------------------------------------

**PARTE 2: Métodos de Validación y Limpieza de NaN**

Inspeccionar el DataFrame base

In [ ]:
poblacion

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo              12.0        23        15   28.0
coyote             NaN         4        23   46.0
jaguar             NaN        25         2   14.0
cerdo salvaje      2.0        21       120  156.0
tapir              4.0         9        40   79.0
venado             2.0       121       121   12.0
ocelote           14.0         1         0    2.0
puma               5.0         2         5    NaN

Método .isna()

In [ ]:
poblacion.isna()

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             False     False     False  False
coyote            True     False     False  False
jaguar            True     False     False  False
cerdo salvaje    False     False     False  False
tapir            False     False     False  False
venado           False     False     False  False
ocelote          False     False     False  False
puma             False     False     False   True

Método .notna()

In [ ]:
poblacion.notna()

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo              True      True      True   True
coyote           False      True      True   True
jaguar           False      True      True   True
cerdo salvaje     True      True      True   True
tapir             True      True      True   True
venado            True      True      True   True
ocelote           True      True      True   True
puma              True      True      True  False

Conteo de nulos con .isna().sum()

In [ ]:
poblacion.isna().sum()

Norte_I     2
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

Eliminación de registros incompletos con .dropna()

In [ ]:
poblacion.dropna()

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo              12.0        23        15   28.0
cerdo salvaje      2.0        21       120  156.0
tapir              4.0         9        40   79.0
venado             2.0       121       121   12.0
ocelote           14.0         1         0    2.0